### PR TITLE
Improved version list if its thers no version available

### LINKED ISSUE #357: [Versions] Empty versions list
The empty versions list is currently displayed like this:

image

We should hide the buttons and display somehow a nicely formatted message "No versions available" or similar.

Related to #349

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request
Resolves #357

### CODE REVIEW

**Comment by Corepex** [comment]
@markus-moser another option would be to just disable the buttons - it looks a bit empty with just the headline and the text - WDYT?

**Comment by Corepex** [comment]
Finalized design from @idaiv https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3021-140611&t=RjgKb95I2NTFB3uq-4

**Review by markus-moser — CHANGES_REQUESTED** [review]
Is it possible to vertical center the message?

On a small screen it currently could look like this:

image

Whereas on a large screen like this:

image

The rest LGTM 👍

**Review by markus-moser — APPROVED** [review]
LGTM

**Pull request merged**
