### PR TITLE
426 emtpy screen notes events

### LINKED ISSUE #426: [Notes&Events] Implement empty screen
Please add a empty note the same way like already implemented for versions when the list of notes&events is empty:

image

### PR DESCRIPTION
**Pull request by xIrusux**
## Changes in this pull request

empty screen for notes and events

image

Resolves #426

### CODE REVIEW

**Comment by markus-moser** [comment]
@xIrusux Please always add a link to the resolved issue to your PR like this, thanks:

Resolves #426

**Review by vin0401 — CHANGES_REQUESTED** [review]
Code wise it looks good to me, but aren't we missing the button to add items to the list? :P

**Comment by xIrusux** [comment]
:) 

https://github.com/user-attachments/assets/28f83b60-24f0-4591-9aaa-1bb9897acfe7

also tiny clean up of some bits as few styles are out of the box with flex anyway. Let me know if we rather want to be explicit. 

EDIT: made header bold so to match with most other headers we are not mega consistent here

**Review by markus-moser — APPROVED** [review]
Everything works like it should. The bold headline is correct. At the end the headline should be bold in all tabs. We should create a shared component for this, but let's create a separate issue for this.

**Comment by markus-moser** [comment]
Separate issue for the headline topic #463

**Pull request merged**
